### ISSUE TITLE
Take counter window error: Attempt to call a nil value

### ISSUE THREAD

**Issue by FabiB98** [chmaha/ReaClassical#171]
Hi,
when I want to open the Take counter window by pressing [Ctrl] + [Enter] I see the following ReaScriptError:
ReaClassical_Take Counter.lua:138: attempt to call a nil value (global 'SNM_SetStringConfigVar')

Do you have an idea what is going wrong?
Thanks in advance and best regards
Fabian

![image](https://github.com/user-attachments/assets/7acfa393-29cb-4a18-9330-927305092ad5)

**Comment by chmaha** [comment]
Looks like you have maybe installed ReaClassical functions inside an existing REAPER install? If you are not using the recommended ReaClassical portable install (see https://github.com/chmaha/ReaClassical/blob/main/install_instructions.md), you are probably missing SWS/S&M extensions which can be downloaded from https://www.sws-extension.org/. If this isn't the solution, let me know full details of your system, how you installed etc.

**Comment by FabiB98** [comment]
Hi, thanks a lot for your quick reply!
I am not using a portable installation. Instead I am using a full installation.
Tthe sws extension was the issue. After installing this everything worked out well.  :)
Thanks a lot and sorry for the mistake!


Thanks a lot!
Best regards
Fabian

**Comment by chmaha** [comment]
Just be careful inside a REAPER installation if updating via Shift+U to NOT say yes to overwriting the custom keymap otherwise you'll lose any shortcuts you've personally set up ;) Updating just the functions from inside ReaPack is probably best...
