### ISSUE TITLE
Track numbering

### ISSUE THREAD

**Issue by FabiB98** [chmaha/ReaClassical#175]
Hi,
one short question regarding the track numbering in the horizontal editing/recording mode.
I have created a project with 17 tracks.
Why does the first track start with track number 17? This is a bit problematic due to my DAW controller. As the device is assuming that the "first" track is really track number 1.
Is there a possibility to change the track number after creating this project?

Thanks in advance!

![image](https://github.com/user-attachments/assets/369cd193-35c5-4f14-91ed-6d02a492db35)

**Comment by chmaha** [comment]
No I'm afraid not. What you are referring to as the first track is in fact the first "mixer" track. The first regular track is 1 however in ReaClassical the mixer is an independent entity like in Merging Pyramix. It has lots of benefits including that fx only need to be added once to the mixer (M:) tracks and all the regular tracks route appropriately. This is most obvious when using vertical workflow. It's a paradigm shift from regular daws.

**Comment by chmaha** [comment]
BTW, name your tracks in the arrange window then press F7 again to sync the naming to the mixer tracks. In ReaClassical 25.x I will move everything but the record input selection to the mixer panel for consistency (big job!).

**Comment by FabiB98** [comment]
Thanks for your prompt reply!
But then this means that it is impossible to use ReaClassical with DAW controllers, correct? I am Using a LogicPad via TouchOSC.

**Comment by chmaha** [comment]
I'm not sure honestly as I've never used one. Is it not possible to assign whatever the first mixer track number is to the first control? If this is the sort of thing possible via REAPER, I can certainly try to make this happen. You'll have to let me know.

**Comment by FabiB98** [comment]
Not really. Because the standard is that all DAW controllers start with track 1. The problem is also, depending on the track number of the Reaper project the first mixer track number is different. Therefore, it is not a constant shift that can be programmed in the DAW controller.

If you see any possibility to adapt the ReaClassical scripts that the mixer tracks start with number 1 this would be awesome! Maybe shift the first tracks to the end? Then everything is solved. It is just important that the mixer tracks are at the beginning.

**Comment by chmaha** [comment]
Hmm, that's tricky because currently many of the S-D edits and album mastering functions assume the track numbered 1 (or strictly 0) is the destination parent track. I suppose down the line I could re-design to accommodate this. However, it's certainly a niche ask in classical music circles and dare I say a massive coding exercise to change a **lot** of functionality. There are 22 instances of directly calling for GetTrack(0, 0) (easy enough to change) but then mass amounts of other internal functions that follows on from that assuming location of regular tracks. Anything is possible, of course, but it might be one of the first requests that I'd say that might need to be sponsored (something I've not had to look into so far).

**Comment by FabiB98** [comment]
I totally understand your comment! I will also think about this issue and try to find a workaround.

**Comment by FabiB98** [comment]
Now I found a solution:
With ReaLearn it is possible to configure in a way to use the first track that is part of the Mixer (MXP).

![image](https://github.com/user-attachments/assets/f3db3019-42dd-4c12-b27d-39c8255737bb)

So now everything is working perfectly!
Best regards

**Comment by chmaha** [comment]
Would you be willing to give me a step-by-step on how to do this? I'd like to add this to the ReaClassical Manual. I'll credit you in a footnote, of course however you'd like.

**Comment by FabiB98** [comment]
> Would you be willing to give me a step-by-step on how to do this? I'd like to add this to the ReaClassical Manual. I'll credit you in a footnote however you'd like.

It is realatively simple:

1. Download & Install ReaLearn package: https://www.helgoboss.org/projects/realearn
2. Open Monitoring Fx (View -> Monitoring Fx)
3. Add ReaLearn instance
4. Configure your Input and output device settings (screenshot (1))
5. Click "Add one" button (screenshot (2))
6. Learn source ((3))
7. Configure function/target by selecting type (4)
8. IMPORTANT: Select Track (5): "<Dynamic (MCP)" and set index (6)--> This uses not track number x, instead the xth track number (shown in the Mixer Panel) is chosen
9. Repeat this for all required remote control items

Hope this helps. You don´t have to credit me in the manual. :-) 

![image](https://github.com/user-attachments/assets/a229c558-ac57-44b0-8db3-2ef520771de9)
![image](https://github.com/user-attachments/assets/fc0f62b3-920c-48b3-8528-0201d4903976)
